language: python
python:
  - "2.7"
  - "3.5"
before_install: pip install pre-commit
script: pre-commit run --all-files --show-diff-on-failure
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
